from ctypes import c_uint32, c_int32
from enum import IntFlag, IntEnum


class PICO_RATIO_MODE(IntEnum):
    PICO_RATIO_MODE_AGGREGATE = 1
    PICO_RATIO_MODE_DECIMATE = 2
    PICO_RATIO_MODE_AVERAGE = 4
    PICO_RATIO_MODE_DISTRIBUTION = 8
    PICO_RATIO_MODE_SUM = 16
    PICO_RATIO_MODE_TRIGGER_DATA_FOR_TIME_CALCULATION = 0x10000000
    PICO_RATIO_MODE_SEGMENT_HEADER = 0x20000000
    PICO_RATIO_MODE_TRIGGER = 0x40000000
    PICO_RATIO_MODE_RAW = 0x80000000


PICO_RATIO_MODE_T = c_uint32


class PICO_CHANNEL(IntEnum):
    PICO_CHANNEL_A = 0
    PICO_CHANNEL_B = 1
    PICO_CHANNEL_C = 2
    PICO_CHANNEL_D = 3
    PICO_CHANNEL_E = 4
    PICO_CHANNEL_F = 5
    PICO_CHANNEL_G = 6
    PICO_CHANNEL_H = 7
    PICO_PORT0 = 128
    PICO_PORT1 = 129
    PICO_PORT2 = 130
    PICO_PORT3 = 131
    PICO_EXTERNAL = 1000
    PICO_TRIGGER_AUX = 1001
    PICO_PULSE_WIDTH_SOURCE = 0x10000000
    PICO_DIGITAL_SOURCE = 0x10000001


PICO_CHANNEL_T = c_int32


class PICO_CHANNEL_FLAGS(IntFlag):
    PICO_CHANNEL_A_FLAGS = 1
    PICO_CHANNEL_B_FLAGS = 2
    PICO_CHANNEL_C_FLAGS = 4
    PICO_CHANNEL_D_FLAGS = 8
    PICO_CHANNEL_E_FLAGS = 16
    PICO_CHANNEL_F_FLAGS = 32
    PICO_CHANNEL_G_FLAGS = 64
    PICO_CHANNEL_H_FLAGS = 128
    PICO_PORT0_FLAGS = 65536
    PICO_PORT1_FLAGS = 131072
    PICO_PORT2_FLAGS = 262144
    PICO_PORT3_FLAGS = 524288


PICO_CHANNEL_FLAGS_T = c_int32


class PICO_PORT_DIGITAL_CHANNEL(IntEnum):
    PICO_PORT_DIGITAL_CHANNEL0 = 0
    PICO_PORT_DIGITAL_CHANNEL1 = 1
    PICO_PORT_DIGITAL_CHANNEL2 = 2
    PICO_PORT_DIGITAL_CHANNEL3 = 3
    PICO_PORT_DIGITAL_CHANNEL4 = 4
    PICO_PORT_DIGITAL_CHANNEL5 = 5
    PICO_PORT_DIGITAL_CHANNEL6 = 6
    PICO_PORT_DIGITAL_CHANNEL7 = 7


PICO_PORT_DIGITAL_CHANNEL_T = c_int32


class PICO_DATA_TYPE(IntEnum):
    PICO_INT8_T = 0
    PICO_INT16_T = 1
    PICO_INT32_T = 2
    PICO_UINT32_T = 3
    PICO_INT64_T = 4


PICO_DATA_TYPE_T = c_int32


class PICO_COUPLING(IntEnum):
    PICO_AC = 0
    PICO_DC = 1
    PICO_DC_50OHM = 50


PICO_COUPLING_T = c_int32


class PICO_BANDWIDTH_LIMITER_FLAGS(IntFlag):
    PICO_BW_FULL_FLAG = 1 << 0
    PICO_BW_20KHZ_FLAG = 1 << 1
    PICO_BW_100KHZ_FLAG = 1 << 2
    PICO_BW_1MHZ_FLAG = 1 << 3
    PICO_BW_20MHZ_FLAG = 1 << 4
    PICO_BW_200MHZ_FLAG = 1 << 5


PICO_BANDWIDTH_LIMITER_FLAGS_T = c_int32


class PICO_BANDWIDTH_LIMITER(IntEnum):
    PICO_BW_FULL = 0
    PICO_BW_100KHZ = 100000
    PICO_BW_20KHZ = 20000
    PICO_BW_1MHZ = 1000000
    PICO_BW_20MHZ = 20000000
    PICO_BW_25MHZ = 25000000
    PICO_BW_50MHZ = 50000000
    PICO_BW_60MHZ = 60000000
    PICO_BW_100MHZ = 100000000
    PICO_BW_200MHZ = 200000000
    PICO_BW_250MHZ = 250000000
    PICO_BW_300MHZ = 300000000
    PICO_BW_350MHZ = 350000000
    PICO_BW_500MHZ = 500000000


PICO_BANDWIDTH_LIMITER_T = c_int32


class PICO_PULSE_WIDTH_TYPE(IntEnum):
    PICO_PW_TYPE_NONE = 0
    PICO_PW_TYPE_LESS_THAN = 1
    PICO_PW_TYPE_GREATER_THAN = 2
    PICO_PW_TYPE_IN_RANGE = 3
    PICO_PW_TYPE_OUT_OF_RANGE = 4


class PICO_SWEEP_TYPE(IntEnum):
    PICO_UP = 0
    PICO_DOWN = 1
    PICO_UPDOWN = 2
    PICO_DOWNUP = 3


class PICO_WAVE_TYPE(IntEnum):
    PICO_SINE = 0x00000011
    PICO_SQUARE = 0x00000012
    PICO_TRIANGLE = 0x00000013
    PICO_RAMP_UP = 0x00000014
    PICO_RAMP_DOWN = 0x00000015
    PICO_SINC = 0x00000016
    PICO_GAUSSIAN = 0x00000017
    PICO_HALF_SINE = 0x00000018
    PICO_DC_VOLTAGE = 0x00000400
    PICO_PWM = 0x00001000
    PICO_WHITENOISE = 0x00002001
    PICO_PRBS = 0x00002002
    PICO_ARBITRARY = 0x10000000


class PICO_SIGGEN_TRIG_TYPE(IntEnum):
    PICO_SIGGEN_RISING = 0
    PICO_SIGGEN_FALLING = 1
    PICO_SIGGEN_GATE_HIGH = 2
    PICO_SIGGEN_GATE_LOW = 3


class PICO_SIGGEN_TRIG_SOURCE(IntEnum):
    PICO_SIGGEN_NONE = 0
    PICO_SIGGEN_SCOPE_TRIG = 1
    PICO_SIGGEN_AUX_IN = 2
    PICO_SIGGEN_EXT_IN = 3
    PICO_SIGGEN_SOFT_TRIG = 4
    PICO_SIGGEN_TRIGGER_RAW = 5


class PICO_SIGGEN_FILTER_STATE(IntEnum):
    PICO_SIGGEN_FILTER_AUTO = 0
    PICO_SIGGEN_FILTER_OFF = 1
    PICO_SIGGEN_FILTER_ON = 2


class PICO_SIGGEN_PARAMETER(IntEnum):
    PICO_SIGGEN_PARAM_OUTPUT_VOLTS = 0
    PICO_SIGGEN_PARAM_SAMPLE = 1
    PICO_SIGGEN_PARAM_BUFFER_LENGTH = 2


class PICO_TIME_UNITS(IntEnum):
    PICO_FS = 0
    PICO_PS = 1
    PICO_NS = 2
    PICO_US = 3
    PICO_MS = 4
    PICO_S = 5


PICO_TIME_UNITS_T = c_int32


class PICO_THRESHOLD_DIRECTION(IntEnum):
    PICO_ABOVE = 0
    PICO_BELOW = 1
    PICO_RISING = 2
    PICO_FALLING = 3
    PICO_RISING_OR_FALLING = 4
    PICO_ABOVE_LOWER = 5
    PICO_BELOW_LOWER = 6
    PICO_RISING_LOWER = 7
    PICO_FALLING_LOWER = 8
    PICO_INSIDE = PICO_ABOVE
    PICO_OUTSIDE = PICO_BELOW
    PICO_ENTER = PICO_RISING
    PICO_EXIT = PICO_FALLING
    PICO_ENTER_OR_EXIT = PICO_RISING_OR_FALLING
    PICO_POSITIVE_RUNT = 9
    PICO_NEGATIVE_RUNT = 10
    PICO_NONE = PICO_RISING


PICO_THRESHOLD_DIRECTION_T = c_int32


class PICO_THRESHOLD_MODE(IntEnum):
    PICO_LEVEL = 0
    PICO_WINDOW = 1


PICO_THRESHOLD_MODE_T = c_int32


class PICO_ETS_MODE(IntEnum):
    PICO_ETS_OFF = 0
    PICO_ETS_FAST = 1
    PICO_ETS_SLOW = 2


class PICO_INDEX_MODE(IntEnum):
    PICO_SINGLE = 0
    PICO_DUAL = 1
    PICO_QUAD = 2


class PICO_ACTION(IntFlag):
    PICO_CLEAR_ALL = 0x00000001
    PICO_ADD = 0x00000002
    PICO_CLEAR_THIS_DATA_BUFFER = 0x00001000
    PICO_CLEAR_WAVEFORM_DATA_BUFFERS = 0x00002000
    PICO_CLEAR_WAVEFORM_READ_DATA_BUFFERS = 0x00004000


PICO_ACTION_T = c_uint32


class PICO_TRIGGER_STATE(IntEnum):
    PICO_CONDITION_DONT_CARE = 0
    PICO_CONDITION_TRUE = 1
    PICO_CONDITION_FALSE = 2


PICO_TRIGGER_STATE_T = c_int32


class PICO_DEVICE_RESOLUTION(IntEnum):
    PICO_DR_8BIT = 0
    PICO_DR_12BIT = 1
    PICO_DR_14BIT = 2
    PICO_DR_15BIT = 3
    PICO_DR_16BIT = 4
    PICO_DR_10BIT = 10
    PICO_DR_10BIT_TURBO = 0x1A


PICO_DEVICE_RESOLUTION_T = c_int32


class PICO_READ_SELECTION(IntEnum):
    PICO_READSELECTION_NONE = 0
    PICO_TRIGGER_READ = 1
    PICO_DATA_READ1 = 2
    PICO_DATA_READ2 = 3
    PICO_DATA_READ3 = 4


PICO_READ_SELECTION_T = c_int32


class PICO_TRIM_ACTION(IntEnum):
    PICO_OLDEST = 0
    PICO_RECENT = 1


class PICO_DIGITAL_PORT_HYSTERESIS(IntEnum):
    PICO_VERY_HIGH_400MV = 0
    PICO_HIGH_200MV = 1
    PICO_NORMAL_100MV = 2
    PICO_LOW_50MV = 3


PICO_DIGITAL_PORT_HYSTERESIS_T = c_int32


class PICO_DIGITAL_DIRECTION(IntEnum):
    PICO_DIGITAL_DONT_CARE = 0
    PICO_DIGITAL_DIRECTION_LOW = 1
    PICO_DIGITAL_DIRECTION_HIGH = 2
    PICO_DIGITAL_DIRECTION_RISING = 3
    PICO_DIGITAL_DIRECTION_FALLING = 4
    PICO_DIGITAL_DIRECTION_RISING_OR_FALLING = 5
    PICO_DIGITAL_MAX_DIRECTION = 6


PICO_DIGITAL_DIRECTION_T = c_int32


class PICO_CONDITIONS_INFO(IntEnum):
    PICO_CLEAR_CONDITIONS = 0x00000001
    PICO_ADD_CONDITION = 0x00000002


class PICO_CLOCK_REFERENCE(IntEnum):
    PICO_INTERNAL_REF = 0
    PICO_EXTERNAL_REF = 1


PICO_CLOCK_REFERENCE_T = c_int32


class PICO_TRIGGER_WITHIN_PRE_TRIGGER(IntEnum):
    PICO_DISABLE = 0
    PICO_ARM = 1


class PICO_TEMPERATURE_REFERENCE(IntEnum):
    PICO_TEMPERATURE_UNINITIALISED = 0
    PICO_TEMPERATURE_NORMAL = 1
    PICO_TEMPERATURE_WARNING = 2
    PICO_TEMPERATURE_CRITICAL = 3


PICO_TEMPERATURE_REFERENCE_T = c_int32


class PICO_DIGITAL_PORT(IntEnum):
    PICO_DIGITAL_PORT_NONE = 0
    PICO_DIGITAL_PORT_MSO_POD = 1000
    PICO_DIGITAL_PORT_UNKNOWN_DEVICE = -2


PICO_DIGITAL_PORT_T = c_int32


class PICO_USB_POWER_DELIVERY_DEVICE_TYPE(IntEnum):
    Nothing = 0
    Source = 2
    Debug = 3


PICO_USB_POWER_DELIVERY_DEVICE_TYPE_T = c_int32


class PICO_LED_SELECT(IntEnum):
    PICO_LED_CHANNEL_A = 0x00000000
    PICO_LED_CHANNEL_B = 0x00000001
    PICO_LED_CHANNEL_C = 0x00000002
    PICO_LED_CHANNEL_D = 0x00000003
    PICO_LED_CHANNEL_E = 0x00000004
    PICO_LED_CHANNEL_F = 0x00000005
    PICO_LED_CHANNEL_G = 0x00000006
    PICO_LED_CHANNEL_H = 0x00000007
    PICO_LED_AWG = 0x00010000
    PICO_LED_AUX = 0x00020000


PICO_LED_SELECT_T = c_int32


class PICO_LED_STATE(IntEnum):
    PICO_LED_AUTO = -1
    PICO_LED_OFF = 0
    PICO_LED_ON = 1


PICO_LED_STATE_T = c_int32


class PICO_TEXT_FORMAT(IntEnum):
    PICO_JSON_DATA = 0
    PICO_JSON_SCHEMA = 1


class PICO_AUXIO_MODE(IntEnum):
    PICO_AUXIO_INPUT = 0
    PICO_AUXIO_HIGH_OUT = 1
    PICO_AUXIO_LOW_OUT = 2
    PICO_AUXIO_TRIGGER_OUT = 3
